### ISSUE TITLE
Consider upgrading to Sphinx 2.x

### ISSUE THREAD

**Issue by joostverburg** [mghro/sphinx-aws-docker#1]
Several extensions for Sphinx are no longer compatible with Sphinx 1.x but require Sphinx 2.x. It would therefore be nice to upgrade.

The current left side navigation menu style does not work properly with Sphinx 2.x.

**Comment by tmadden** [comment]
I agree. I have too many clinical developments going on at the moment to work on this, but I'll put it on my radar for later this fall...

**Comment by tmadden** [comment]
I made a 2.0.0 release of the documentation system that uses Sphinx 3.x. You won't get it automatically, but it's very simple to opt into using it. See here:

https://github.com/mghro/documentation-scripts/releases/tag/2.0.0

I'm assuming that Sphinx 3.x meets your needs. If for some reason you specifically need 2.x, feel free to reopen this.
